apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgfdss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dgfdss
  template:
    metadata:
      labels:
        app: dgfdss
    spec:
      containers:
      - image: okteto.dev/dgfdss:latest
        name: dgfdss
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "736b1df1-fd6a-4165-8015-9bbfcff514cd"
        - name: Vless_Path
          value: "/736b1df1-fd6a-4165-8015-9bbfcff514cd-vless"
        - name: Vmess_UUID
          value: "736b1df1-fd6a-4165-8015-9bbfcff514cd"
        - name: Vmess_Path
          value: "/736b1df1-fd6a-4165-8015-9bbfcff514cd-vmess"
        - name: Share_Path
          value: "/v2lineek"
